services:
  deepsearcher:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/config/config.yaml
      - ./documents:/data/documents
    environment:
      - MAX_WORKERS=2  # Can be overridden at runtime
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '2'  # Limit CPU usage
    #      memory: 4G  # Limit memory usage
    #    reservations:
    #      cpus: '1'
    #      memory: 2G
    restart: unless-stopped
